### ISSUE TITLE
Unable to change config file

### ISSUE THREAD

**Issue by harrystuart** [hcmlab/emovoice#10]
I would like to be able to set the path of the `.wav` file to be tested and the `result` file produced to values entered as arguments when running `do_run linsvm compare`. Something like `do_run linsvm compare path\of\wav path\of\result`. The problem is, at least for the path of the `.wav` file, it appears as if it is determined by the `emovoice.pipeline-config` file only.

I can't seem to be able to change the value of the path any way other than directly from the config file. I tried setting `%CONFIG%` in `do_run.cmd` to a different config file I created but when running the command, the configuration always defaults to `emovoice.pipeline-config`. What would I need to do look at doing to set the path as an argument when running the command?

Thanks

**Comment by frankenjoe** [comment]
As documented [here](
https://rawgit.com/hcmlab/ssi/master/docs/index.html#variables) you can use the `-confstr` parameter of `xmlpipe.exe`.

In `do_run.cmd` change:

`%ROOT%bin\xmlpipe.exe -log ssi.log -config %CONFIG% %PIPELINE%`

to 

`%ROOT%bin\xmlpipe.exe -log ssi.log -confstr "audio:file=%3" -config %CONFIG% %PIPELINE%`

**Comment by harrystuart** [comment]
Perfect, thank you!

**Comment by Rojina99** [comment]
@HStuart18 can you give me idea like how you tested on your own wav audio file. I tried changing audio file path in emovoice.pipeline-config to audio path of my audio file.

But it is giving me error:

![error2](https://user-images.githubusercontent.com/13509437/65120366-3af3d880-da0d-11e9-8500-7096122d86fe.jpg)


So, I wanted to know how you were able to test own your audio file.

_Note: When I run audio files created in combined folder using command_
` do_vad 48000 "anger;boredom;calm;disgust;fear;happiness;neutral;sadness" `
_it works fine . _

**Comment by Rojina99** [comment]
Found out what was causing the error. Bit rate of input file was expected to be 768 kbps but was audio wav with bit rate 1536 kbps.
