### ISSUE TITLE
Run xmlpipe.exe --quiet

### ISSUE THREAD

**Issue by gustavotrott** [hcmlab/emovoice#11]
Hello, I'm using emovoice to analyse some calls from `.wav` files.
It's working pretty well. My problem is that I have thousands of files to process, and I don't need to see the process in real time.

I'm running with default configs and using the command:
`bin\xmlpipe.exe -confstr "file=myaudio" -config emovoice.pipeline-config  emovoice.pipeline`

Is there any way to run xmlpipe.exe in background mode and in a faster way? I don't need to see graphics, I just want the output xml file.

Thank you

**Comment by frankenjoe** [comment]
Unfortunately there is no easy way to run `EmoVoice` offline. 

To hide the graphics open `emovoice.pipeline` and remove the following lines:

```
	<!-- visualization -->	
	<consumer create="SignalPainter:plot" title="AUDIO - RAW" size="10" type="2" autoscale="false" fix="-1.0,1.0">
		<input pin="audio" frame="0.02s"/>
	</consumer>
	<consumer create="SignalPainter:plot" title="AUDIO - ACTIVITY" size="10" type="0">
		<input pin="vad" frame="0.02s"/>
        </consumer> 
```

Also, if you want to loop over all your files, I suggest to use the `file` variable to get a unique output name for each processed file:

```
	<object create="FileEventWriter" path="$(audio:file)">
		<listen address="emotion@audio"/>
        </object>
```
