### ISSUE TITLE
None of the commands work

### ISSUE THREAD

**Issue by Akaysimmer** [hcmlab/emovoice#12]
Install.cmd does not install the core tools to the bin/ folder
The installation ends here for me and does not give me an error message
![screenshot 163](https://user-images.githubusercontent.com/45009185/53113189-e81a7700-3538-11e9-97e4-f9768876cf55.png)

I ran do_data and it says cannot find the download.zip file..? That file isn't part of your repository. Here's the error message i get..
![screenshot 167](https://user-images.githubusercontent.com/45009185/53113244-084a3600-3539-11e9-911d-ac6fd601c062.png)

I have Python 3.7 already added to path

**Comment by frankenjoe** [comment]
It looks like the blank in the path is causing the trouble. Could you please try from a folder that has no blank in the path to see if it solves your problem.
