### ISSUE TITLE
avcodec-57.dll not found

### ISSUE THREAD

**Issue by haeferer** [hcmlab/emovoice#13]
Hi, first, thx for your great work.
Right now i try to follow your tutorial, but 
executing do_sample runs in an error

xmlchain.exe avcodec-57.dll is missing 

????

Thx for any help

**Comment by haeferer** [comment]
xmlchain command is

D:\keastick\RemoteRep\emovoice\bin\xmlchain.exe -list -anno D:\keastick\RemoteRep\emovoice\data\combined\~anno.txt -parallel 4  D:\keastick\RemoteRep\emovoice\c
hains\compare D:\keastick\RemoteRep\emovoice\data\combined\~stream.txt D:\keastick\RemoteRep\emovoice\data\combined\~sample.txt

**Comment by frankenjoe** [comment]
Download [ffmpeg](https://ffmpeg.zeranoe.com/builds/ ) and copy files from `bin` in the folder of `xmlchain.exe`.

EDIT: as pointed out by @haeferer requires version 3.4.x

**Comment by haeferer** [comment]
Wow, thx for your fast response. Works, but you have to download version 3.4.x (3.4.2 latest) cause 4.x does not work. (https://ffmpeg.zeranoe.com/builds/win64/)

thx

**Comment by haeferer** [comment]
Fixed
