### ISSUE TITLE
Emovoice Live is giving Error

### ISSUE THREAD

**Issue by Rojina99** [hcmlab/emovoice#17]
Previously running live audio in emovoice worked completely fine.

I am running emovoice pipeline using command 
`bin\xmlpipe.exe -confstr "file=myaudio" emovoice.pipeline`

Here, I set my emovoive pipeline config as 
`audio:live = True`

Previously this used to work completely fine but now this is giving me error

![emovoicelive](https://user-images.githubusercontent.com/13509437/67380626-5b81f600-f5aa-11e9-8262-3fe9f0a99ad5.png)

I am unable to figure out why.

**Comment by shelm** [comment]
Did you change anything in the pipeline? We tried to reproduce your error with a clean checkout but it works fine in our case. 
Also why  do you set "file=myaudio" if you want to use live input?

**Comment by Rojina99** [comment]
As far as I know I have not changed anything different from the one I was doing the day before. It was working absolutely fine but now it is not. 

`file=myaudio` is for output xml file not for input file. It generates myaudio.events which has is xml file output. For recorded audio I am passing 

`bin\xmlpipe.exe -confstr "file=myaudio;audio:file=data\path_to_recorded_audio" emovoice.pipeline`

and its working fine.
