### ISSUE TITLE
Help required to get it running.

### ISSUE THREAD

**Issue by kirushan** [hcmlab/emovoice#2]
When I execute do_all.cmd I get the following warning in the system. I have python 3.7 installed but its not recognized as well. I have attached a screenshot of the cmd view I get after executing the do_all.cmd.

It will be a great help if you could help me with this.

![warning](https://user-images.githubusercontent.com/20640543/45402007-0c605680-b671-11e8-9521-b1da9186349c.png)

**Comment by frankenjoe** [comment]
Please install Python 3.x and make sure it's part of the system path.

**Comment by frankenjoe** [comment]
Is Python part of the system path?

**Comment by kirushan** [comment]
Python wasn't a path of the system path. Its fixed now. Could you please assist me with the 2 warnings below where the github urls don't exist

**Comment by frankenjoe** [comment]
The files do exist, so maybe it is related to a firewall setting? In the latest commit the curl error message will be displayed if the url is not found. Hopefully this will provide you a hint what's going wrong...
