### ISSUE TITLE
need a help

### ISSUE THREAD

**Issue by uneverknwwhoim** [hcmlab/emovoice#3]
Can you help me .. how to run this ?? i am beginner.. i request you to plz help me.. i have some idea about python

**Comment by shelm** [comment]
Please have a look  at the documentation first: 
https://rawgit.com/hcmlab/emovoice/master/docs/index.html
If you have any further specific problems we are happy to help.

**Comment by uneverknwwhoim** [comment]
can you just help me how to run ?
