### ISSUE TITLE
Can i get the XML output written to a XML file?

### ISSUE THREAD

**Issue by Nixon1979** [hcmlab/emovoice#4]
It works like a charm, but wanted to check if i can get the XML output instead of a live feed on the screen on to a file? Wanted to use that data and analyse it further.

**Comment by frankenjoe** [comment]
Open `emovoice.pipeline` in a text editor and add the following files at the end of the pipeline:

``` xml
	<register>	
		<load name="ioput"/>			
	</register>
	<object create="FileEventWriter" path="emovoice">
		<listen address="emotion@audio"/>
	</object>
```

this will give you a file `emovoice.events` in the root folder containing the classification results in the following format:

``` xml
<?xml version="1.0" ?>
<events ssi-v="2">
    <event sender="audio" event="emotion" from="120" dur="1650" prob="1.000000" type="MAP" state="COMPLETED" glue="0">
        <tuple string="anger" value="0.957972" />
        <tuple string="boredom" value="0.000011" />
        <tuple string="disgust" value="0.005396" />
        <tuple string="fear" value="0.011940" />
        <tuple string="happiness" value="0.024572" />
        <tuple string="neutral" value="0.000109" />
        <tuple string="sadness" value="0.000001" />
    </event>
    <event sender="audio" event="emotion" from="2970" dur="1920" prob="1.000000" type="MAP" state="COMPLETED" glue="0">
        <tuple string="anger" value="0.978200" />
        <tuple string="boredom" value="0.000001" />
        <tuple string="disgust" value="0.017050" />
        <tuple string="fear" value="0.001303" />
        <tuple string="happiness" value="0.001324" />
        <tuple string="neutral" value="0.002122" />
        <tuple string="sadness" value="0.000000" />
    </event>
    ...
</events>
```

**Comment by Nixon1979** [comment]
Thanks a lot, will check this.. A quick question, is there anyway I can process multiple audio files in parallel? And get the output in different files?

**Comment by Nixon1979** [comment]
> Open `emovoice.pipeline` in a text editor and add the following files at the end of the pipeline:
> 
> ```
> 	<register>	
> 		<load name="ioput"/>			
> 	</register>
> 	<object create="FileEventWriter" path="emovoice">
> 		<listen address="emotion@audio"/>
> 	</object>
> ```
> 
> this will give you a file `emovoice.events` in the root folder containing the classification results in the following format:
> 
> ```
> <?xml version="1.0" ?>
> <events ssi-v="2">
>     <event sender="audio" event="emotion" from="120" dur="1650" prob="1.000000" type="MAP" state="COMPLETED" glue="0">
>         <tuple string="anger" value="0.957972" />
>         <tuple string="boredom" value="0.000011" />
>         <tuple string="disgust" value="0.005396" />
>         <tuple string="fear" value="0.011940" />
>         <tuple string="happiness" value="0.024572" />
>         <tuple string="neutral" value="0.000109" />
>         <tuple string="sadness" value="0.000001" />
>     </event>
>     <event sender="audio" event="emotion" from="2970" dur="1920" prob="1.000000" type="MAP" state="COMPLETED" glue="0">
>         <tuple string="anger" value="0.978200" />
>         <tuple string="boredom" value="0.000001" />
>         <tuple string="disgust" value="0.017050" />
>         <tuple string="fear" value="0.001303" />
>         <tuple string="happiness" value="0.001324" />
>         <tuple string="neutral" value="0.002122" />
>         <tuple string="sadness" value="0.000000" />
>     </event>
>     ...
> </events>
> ```

This works, perfectly...Thanks a ton..  any possible way I can process multiple audio files in parallel? And get the output in different files?

**Comment by Nixon1979** [comment]
As per the subject this is closed and I am able to get the necessary output.
