### ISSUE TITLE
do_data.cmd not work

### ISSUE THREAD

**Issue by liorsultan9** [hcmlab/emovoice#7]
I tried to click on do_data.cmd nothing was downloaded,  this is the instruction:
"do_data.cmd script next. This will download the audio samples from the Berlin Database of Emotional Speech. The data was recorded as a part of the DFG funded research project SE462/3-1 in 1997 and 1999 and contains a database of emotional utterances spoken by actors. For more information check the references here. After running the script you will find folders for six basic emotions and neutral in the data\\chunks folder including 533 wav files (see next section)."

**Comment by frankenjoe** [comment]
Maybe python 3 is missing or not in the PATH? Otherwise, please execute the batch file from the command line and post the error message.
