### ISSUE TITLE
Implementation with existing application

### ISSUE THREAD

**Issue by harrystuart** [hcmlab/emovoice#9]
This isn't so much an issue, however, I wasn't sure about where else to ask. Say I have a trained model, and would like to to run real time audio recognition in an ASP.NET Core application, how would I go about implementing my model? Essentially, my application has a websocket that is connected to an audio stream, and I would like to attach the model so to speak such that it runs real time emotion detection on the incoming audio. Can I export the model somehow so that I can implement it?

Thanks!

**Comment by frankenjoe** [comment]
sorry, no experience with that. maybe [this](http://tensorflowapi.blogspot.com/2018/03/integrating-tensor-flow-api-into-aspnet.html) will help..

**Comment by harrystuart** [comment]
Thanks for the resource. I would like to know the following as I think it will help me immensley: Once I successfully train the model, a `.model` file is created. If I want to run the model on unknown samples, what files are actually necessary to do so? I assume that the `.pipeline`, `.pipeline-config` files and `.model` files are absolutely necessary. Are there any additional files that I would have to integrate into a different application in order to run the real-time emotion detection pipeline?

Thanks

**Comment by harrystuart** [comment]
@frankenjoe  I managed to successfully implement emovoice into my application by simply adding the files to my applications' folder and executing the processes during my applications' startup. Just before I close the issue, assuming I have trained the model and am ready to run `do_run.cmd`, is it possible to get this to work on Ubuntu?

Thanks

**Comment by frankenjoe** [comment]
Yes, it should work on Ubuntu, have a look at:

https://github.com/hcmlab/mobileSSI

Regarding your earlier question: you can get rid of the countdown by adding:

```
<framework countdown=0/>
```

Instead, you can also start processing by sending a socket command:

https://rawgit.com/hcmlab/ssi/master/docs/index.html#xml-advanced-network-synchronization

**Comment by harrystuart** [comment]
Thanks for the help. If you're familiar at all with mobileSSI on Linux could you please take a look at: https://github.com/hcmlab/mobileSSI/issues/4 ? Thanks for all the help. I'll close this issue.
